# Generated by Django 4.2.3 on 2023-08-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pin_code',
            field=models.IntegerField(),
        ),
    ]
