# Generated by Django 4.2.3 on 2023-08-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_alter_profile_pin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oredr',
            name='pin_code',
            field=models.IntegerField(),
        ),
    ]
