# Generated by Django 4.2.3 on 2023-07-26 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=200)),
                ('category_image', models.ImageField(upload_to='Category_images')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('offer', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=250)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=250)),
                ('product_image1', models.ImageField(upload_to='product_image1')),
                ('product_image2', models.ImageField(upload_to='product_image2')),
                ('product_image3', models.ImageField(upload_to='product_image3')),
                ('product_image4', models.ImageField(upload_to='product_image4')),
                ('product_image5', models.ImageField(upload_to='product_image5')),
                ('original_price', models.FloatField()),
                ('offer_price', models.FloatField()),
                ('description', models.TextField(max_length=500)),
                ('small_description', models.TextField(max_length=250)),
                ('offer', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
